name: ModelEngine
version: R4.0.6
main: com.ticxo.modelengine.core.ModelEngine
load: STARTUP
authors:
  - Ticxo
libraries:
  - net.kyori:adventure-api:4.17.0
  - net.kyori:adventure-text-serializer-gson:4.17.0
  - net.kyori:adventure-text-serializer-bungeecord:4.3.3
commands:
  meg:
    description: All things Model Engine related.
    permission-message: You do not have permission to use this command.
permissions:
  modelengine.command:
    description: Access to all Model Engine commands.
    default: op
api-version: "1.19"
softdepend:
  - MythicMobs
  - Citizens
  - LibsDisguises
  - ViaVersion
folia-supported: true
