
name: Build Jar 
on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    permissions: write-all 
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up JDK 21 
        uses: actions/setup-java@v3  
        with:  
          java-version: '21'  
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTest
        env:
           MAVEN_OPTS: -Xmx2048m --illegal-access=permit
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tooltips
          path: target/tooltips-*.jar
