
name: Build Jar 
on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ] 
jobs: 
  build: 
     permissions: write-all 
     runs-on: ubuntu-latest 
     steps: 
     - uses: actions/checkout@v3 
     - name: Set up JDK 17 
       uses: actions/setup-java@v3 
       with: 
         java-version: '17' 
         distribution: 'temurin' 
     - name: Install depends 
       run: |
        mvn clean package -DskipTests
       env:
        MAVEN_OPTS: -Xmx2048m --illegal-access=permit
     - run: mkdir staging && cp target/*.jar staging 
     - name: Set Release version env variable 
       run: | 
         echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV 
     - name: "Build & test" 
       run: | 
         echo "done!" 
     - uses: "marvinpinto/action-automatic-releases@latest" 
       with: 
         repo_token: "${{ secrets.GITHUB_TOKEN }}" 
         automatic_release_tag: "${{ env.RELEASE_VERSION }}" 
         prerelease: false 
         title: "Release ${{ env.RELEASE_VERSION }}" 
         files: | 
           staging/*.jar

